[build]
  command = "npx vite build --outDir=build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[images]
  remote_images = ["https://ext.same-assets.com/**"]
